# Numpy Practice Starting 

In [1]:
import numpy as np

In [2]:
print("hello Word" )

hello Word


In [3]:
myarr = np.array([[3,6,32,2,7]] , np.int64)

In [4]:
myarr

array([[ 3,  6, 32,  2,  7]], dtype=int64)

In [5]:
myarr[0][0]

3

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr.shape

(1, 5)

In [8]:
myarr[0,1]

6

In [9]:
myarr[0,1] = 64

In [10]:
myarr[0,1]

64

## Array Creations Methods

**There are 5 General meachnaisms for creating arrays**

* Conversion from other Python structures (i.e. lists and tuples)

* Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

* Replicating, joining, or mutating existing arrays

* Reading arrays from disk, either from standard or custom formats

* Creating arrays from raw bytes through the use of strings or buffers

* Use of special library functions (e.g., random)

### Array Creation:  Conversion from other Python structures (i.e. lists and tuples)

In [11]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({34,23,23})

array({34, 23}, dtype=object)

* Generallay hm log array interger or Float k hi bnate hai , dtype object is not efficient 

### Array Creation: Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [19]:
zeros = np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros.shape

(2, 5)

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
rng = np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace = np.linspace(1,50,10)

In [29]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
lspace = np.linspace(1,4,4)

In [31]:
lspace

array([1., 2., 3., 4.])

In [32]:
lspace = np.linspace(1,5,4)

In [33]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [34]:
emp = np.empty((4,6))

In [35]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.45697133e-308, 1.16820707e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.02360935e-306, 1.69120416e-306, 1.78022342e-306],
       [6.23058028e-307, 1.06811422e-306, 9.45699680e-308,
        1.11258854e-306, 1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.42419530e-306,
        6.89805151e-307, 1.78020169e-306, 1.42410974e-306]])

In [38]:
emp_like = np.empty_like(lspace)

In [39]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [40]:
ide = np.identity(45)

In [41]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [42]:
ide.shape

(45, 45)

In [44]:
arr =  np.arange(99)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr.reshape(3,31)

ValueError: cannot reshape array of size 99 into shape (3,31)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [54]:
arr = arr.ravel()

In [55]:
arr.shape

(99,)